<?php
// 2019-05-30 https://github.com/magento/magento2/blob/2.3.1/app/code/Magento/Customer/view/frontend/templates/form/register.phtml
$b = $block; /** @var KingPalm\B2B\Block\Registration $b */
?>
<div class='kingpalm-b2b-registration'>
	<?= df_cc_n(
		$b->cb('is_business', 'Retail Registration?')
		,$b->text('name', 'Business Name')
		,$b->text('dba', 'DBA (Doing Business As)')
		,$b->select('type', 'What type of business do you run?', [
			'Smoke Shop', 'Dispensary', 'Vape Shop', 'Adult Store', 'Gas Station'
			,'Convenience/Liquor/Grocery Store', 'Distributor/Wholesaler', 'Gift/Novelty Shop'
			,'Hookah Lounge/Store', 'Tobacco Store', 'Tattoo Parlor', 'Processor'
		])
		,$b->text('number_of_locations', 'Number of Locations')
		,$b->text('tax', 'TAX ID')
		,$b->text('phone', 'Phone Number')
		,$b->textarea('address', 'Storefront Business Address')
	) ?>
</div>